language: node_js
node_js:
- 13.2.0
dist: trusty
sudo: false
cache:
  directories:
  - node_modules
install:
- npm install -g yarn
script:
- yarn install
deploy:
- provider: script
  on:
    branch: ssr-deploy
  script: openssl aes-256-cbc -K $encrypted_2c5959d3eced_key -iv $encrypted_2c5959d3eced_iv -in scripts/alias.pem.enc -out alias.pem -d && chmod 400 alias.pem && ssh -oStrictHostKeyChecking=no -i alias.pem $SERVER_URL "./deploy.sh"
