language: node_js
node_js:
  - "13.2.0"
dist: trusty
sudo: false

branches:
  only:
  - master
  - /^v\d+\.\d+\.\d+.*$/

cache:
  directories:
    - node_modules

install:
  - npm install -g yarn
  - yarn install

script:
  - yarn build
  - cp CNAME README.md build/

deploy:
  provider: heroku
  api_key: $HEROKU_PRODUCTION_API_KEY
  app: $HEROKU_APP_NAME
  on:
    tags: true
